# Generated by Django 4.2.17 on 2024-12-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'permissions': (('es_miembro_1', 'Es miembro con prioridad 1'), ('development', 'Puede desarrollar'), ('scrum_master', 'Es Scrum Master'), ('product_owner', 'Es Product Owner'))},
        ),
    ]
