# Generated by Django 4.2.17 on 2024-12-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_carmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='condicion_precio',
            field=models.CharField(default='Bajo', max_length=10),
        ),
    ]
