# Generated by Django 4.2.17 on 2024-12-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_carmodel_condicion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='condicion_precio',
            field=models.CharField(max_length=10),
        ),
    ]
