# Generated by Django 4.2.17 on 2024-12-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_carmodel_condicion_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='condicion_precio',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
